//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock_Paper_Scissors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class skin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal skin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rock_Paper_Scissors.skin", typeof(skin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU .
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Wins This Game..
        /// </summary>
        internal static string CPUWin {
            get {
                return ResourceManager.GetString("CPUWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string draw {
            get {
                return ResourceManager.GetString("draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player .
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Wins This Game..
        /// </summary>
        internal static string PlayerWin {
            get {
                return ResourceManager.GetString("PlayerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Paper Covers Rocks.
        /// </summary>
        internal static string reason1 {
            get {
                return ResourceManager.GetString("reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Rock Breaks Scissors.
        /// </summary>
        internal static string reason2 {
            get {
                return ResourceManager.GetString("reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Scissor Cuts Paper.
        /// </summary>
        internal static string reason3 {
            get {
                return ResourceManager.GetString("reason3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds: .
        /// </summary>
        internal static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You took too much time so we chose for you..
        /// </summary>
        internal static string timerprompt {
            get {
                return ResourceManager.GetString("timerprompt", resourceCulture);
            }
        }
    }
}
